# run: conda env create --file environment.yml

name: test_env
dependencies:
  pip:
    - torch = 1.8.0
    - numpy = 1.17.2
    - opencv_python==4.2.0.34
    - nibabel = 3.2.1
    - tqdm = 4.36.1
    - torchvision = 0.9.0
